name: ZipNRlz

on:
  push:
    tags:
    - v*
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: zip it
        run: zip -r service.subtitles.zimukux.zip ./*
        
      - name: release
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "service.subtitles.zimukux.zip"
          token: ${{ secrets.PAT_FOR_ACTIONS }}