name: Zip&Rlz

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: zip it
        run: |
          echo ::set-env name=VER::$(cat addon.xml |grep  -oP 'name="ZiMuKuX" version="\K[^"]*')
          mkdir plugin.subtitles.zimukux
          mv ./* plugin.subtitles.zimukux/
          zip -r plugin.subtitles.zimukux-${{ env.VER }}.zip plugin.subtitles.zimukux/

      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "plugin.subtitles.zimukux-${{ env.VER }}.zip"
          token: ${{ secrets.PAT_FOR_ACTIONS }}