name: Zip&Rlz

on: push
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: check tag
        run: |
          ver=v`cat addon.xml |grep  -oP 'name="ZiMuKuX" version="\K[^"]*'`
          if git rev-parse "$ver" >/dev/null 2>&1; then
            echo "SHOULD_RELEASE=false" >> $GITHUB_ENV;
          else
            echo "SHOULD_RELEASE=true" >> $GITHUB_ENV
          fi
          cat $GITHUB_ENV

      - name: zip it
        if: ${{ env.SHOULD_RELEASE == 'true' }}
        run: |
          ver=`cat addon.xml |grep  -oP 'name="ZiMuKuX" version="\K[^"]*'`
          echo ZIMUKUX_VER=$ver >> $GITHUB_ENV
          for file in .[^.]*; do rm -rf "$file"; done
          cd ..
          mv zimuku_for_kodi/ plugin.subtitles.zimukux/
          zip -r -qq plugin.subtitles.zimukux-$ver.zip plugin.subtitles.zimukux/
          mv plugin.subtitles.zimukux-$ver.zip plugin.subtitles.zimukux/
          mv plugin.subtitles.zimukux/ zimuku_for_kodi/ 

      - name: release
        if: ${{ env.SHOULD_RELEASE == 'true' }}
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ env.ZIMUKUX_VER }}"
          commit: "main"
          artifacts: "plugin.subtitles.zimukux-${{ env.ZIMUKUX_VER }}.zip"
          token: ${{ secrets.PAT_FOR_ACTIONS }}