name: Zip&Rlz

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: zip it
        run: |
          cat addon.xml |grep  -oP 'name="ZiMuKuX" version="\K[^"]*'
          echo "ZIMUKUX_VER=`cat addon.xml |grep  -oP 'name="ZiMuKuX" version="\K[^"]*'`" >> $GITHUB_ENV
          cat $GITHUB_ENV
          cd ..
          mv zimuku_for_kodi/ plugin.subtitles.zimukux/
          zip -r plugin.subtitles.zimukux-${{ env.ZIMUKUX_VER }}.zip plugin.subtitles.zimukux/

      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "plugin.subtitles.zimukux-${{ env.ZIMUKUX_VER }}.zip"
          token: ${{ secrets.PAT_FOR_ACTIONS }}